# Generated by Django 5.0.4 on 2024-05-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_cart_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(choices=[(1, 'shoes'), (2, 'electronic'), (3, 'cloths')], verbose_name='Catagory'),
        ),
    ]
